#
# The following variables need to be defined in the GitLab Project:
#
# - REGISTRY: hostname/path to the docker registry
# - REGISTRY_CONF: b64 encoded docker config.json that allows pushing image(s)
# - DEPLOY_URL: b64 encoded url to trigger the deployment


stages:
  - build
  - post-build  # New post-build stage for curl

# First stage (Kaniko build)
testing-build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+rc[0-9]+$/
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "${REGISTRY_CONF}" | base64 -d > /kaniko/.docker/config.json
    - export TAG="${CI_COMMIT_TAG}"
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --build-arg "version=${CI_COMMIT_TAG}"
      --destination "${REGISTRY}/${CI_PROJECT_NAME}:${TAG%%rc*}rc"
      --destination "${REGISTRY}/${CI_PROJECT_NAME}:${TAG%%.*}rc"
      --destination "${REGISTRY}/${CI_PROJECT_NAME}:testing"


post-build-testing:
  stage: post-build
  needs: 
    - testing-build  # Ensure this runs after testing-build is successful
  image: alpine/curl:latest 
  script:
    - curl -X POST "$(echo ${DEPLOY_URL} | base64 -d)"  


latest-build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+$/
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "${REGISTRY_CONF}" | base64 -d > /kaniko/.docker/config.json
    - export TAG="${CI_COMMIT_TAG}"
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --build-arg "version=${CI_COMMIT_TAG}"
      --destination "${REGISTRY}/${CI_PROJECT_NAME}:${TAG}"
      --destination "${REGISTRY}/${CI_PROJECT_NAME}:${TAG%%.*}"
      --destination "${REGISTRY}/${CI_PROJECT_NAME}:latest"


post-build-latest:
  stage: post-build
  needs:
    - latest-build  
  image: alpine/curl:latest
  script:
    - curl -X POST "$(echo ${DEPLOY_URL} | base64 -d)"